CREATE TABLE `Teacher` (
    Tid         INT NOT NULL AUTO_INCREMENT,
    Title       VARCHAR(255),
    Name        VARCHAR(255) NOT NULL,
    LastName    VARCHAR(255) NOT NULL,
    OldName     VARCHAR(255),
    OldLastName VARCHAR(255),
    Start_Year  YEAR,
    End_Year    YEAR,
    TUGen       INT,
    Sex         BINARY(1),
    NationalID  VARCHAR(13),
    Birthday    YEAR,
    HouseNo     VARCHAR(50),
    Building    VARCHAR(255),
    VillageNo   VARCHAR(50),
    Soi         VARCHAR(255),
    SubDistrict VARCHAR(255),
    District    VARCHAR(255),
    Province    VARCHAR(255),
    PostalCode  VARCHAR(15),
    Country     VARCHAR(255),
    HomeTel     VARCHAR(15),
    Mobile      VARCHAR(15),
    Email       VARCHAR(255),
    PRIMARY KEY (Tid)
);
